carts/urls.py
from django.urls import path
from carts import views
app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('item_remove_cart/<int:pk>/', views.item_remove_cart, name='item_remove_cart'),
    path('item_quantity_minus/<int:pk>/', views.item_quantity_minus, name='item_quantity_minus'),
    path('item_quantity_plus/<int:pk>/', views.item_quantity_plus ,name='item_quantity_plus'),
    
    

]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from carts.views import success
from pages import views
from users.views import guest_register_view, register_page, login_admin

urlpatterns = [
                  path('', views.home, name='home'),
                  path('admin/', admin.site.urls),
                  path('addresses/', include('addresses.urls')),
                  path('users/', include('users.urls')),
                  path('cart/', include('carts.urls')),
                  path('companies/', include('companies.urls.companies')),
                  path('company_users/', include('companies.urls.company_users')),
                  path('comments/', include('comments.urls')),
                  path('categories/', include('categories.urls')),
                  path('data-analysis/', include('data_analysis.urls')),
                  path('fiscal-years/', include('settings.urls.fiscal_years')),
                  path('guest_register/', guest_register_view,
                       name='guest_register'),
                  path('items/', include('items.urls')),
                  path('login_admin/', login_admin, name='login_admin'),
                  path('orders/', include('orders.urls')),
                  path('ratings/', include('ratings.urls')),
                  path('refunds/', include('refunds.urls')),
                  path('register/', register_page, name='register'),
                  path('success/', success, name='success'),
                  path('search_products/', views.search_products,
                       name='search_products'),
                  path('api/v1/data/', include('data_analysis.api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path

from items import views

app_name = 'items'

urlpatterns = [
    path('', views.category_select, name='category_select'),
    path('<int:pk>', views.item_list, name='list'),
    path('<int:pk>/create', views.item_add, name='create'),
    path('<slug:slug>', views.item_detail, name='detail'),
    path('update/<slug:slug>/', views.item_update, name='update'),
    path('<int:pk>/image_remove', views.image_remove, name='image_remove'),
]

items/forms.py
from django import forms
from django.forms import BaseModelFormSet, BaseFormSet

from carts.models import CartItem
from items.models import Item, StockRecord, ItemImage


class BaseItemModelFormSet(BaseModelFormSet):
    def clean(self):
        super(BaseItemModelFormSet, self).clean()


class BaseItemFormSet(BaseFormSet):
    def save(self, commit=True):
        for form in self.forms:
            print(form.cleaned_data)
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description', '')

            item = Item(name=name, description=description)
            item.save()
        return self.forms


class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'name',
            'description',
            'featured',
            'specification'
        ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': ''}),
            'description': forms.Textarea(
                attrs={'class': 'form-control', 'required': 'required', 'placeholder': '', 'row': 1}),
            'specification': forms.Textarea(
                attrs={'class': 'form-control', 'required': 'required', 'placeholder': '', 'row': 1}),

        }

        labels = {
            'name': 'Item Name',
            'description': 'Description',
            'featured': 'Featured It'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class StockForm(forms.ModelForm):
    class Meta:
        model = StockRecord
        fields = [
            'price_excl_tax',
            'discount_percentage',
            'quantity',
        ]

        widgets = {
            'price_excl_tax': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'required', 'placeholder': ''}),
            'discount_percentage': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'required', 'placeholder': ''}),
            'quantity': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': ''})

        }

        labels = {
            'name': 'Item Name',
            'discount_percentage': 'Discount Percent',
            'quantity': 'Stock Quantity'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class QuantityForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = [
            'quantity',
        ]

        widgets = {
            'quantity': forms.Select(
                attrs={'class': 'form-control', 'required': 'required', 'placeholder': 'Quantity'})

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['quantity'].queryset = [1,2,3,4]


class ItemImageForm(forms.ModelForm):
    class Meta:
        model = ItemImage
        fields = [
            'document',
        ]

items/views.py
import decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.forms.models import modelformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from carts.models import Cart, CartItem
from categories.models import Category
from comments.forms import CommentForm
from comments.models import Comment
from items import forms
from items.forms import BaseItemModelFormSet
from items.models import Item, ItemImage
from ratings.forms import RatingForm
from ratings.models import Rating
from settings.models import FiscalYear
from users.decorators import provider_required
from django.db.models import Sum
from users.models import GuestEmail


@login_required
@provider_required
def category_select(request):
    context = {}
    categories = Category.objects.all_active()
    template_name = 'items/category_select.html'
    context['objects'] = categories
    context['count'] = 0
    return render(request, template_name, context)


@login_required
@provider_required
def item_list(request, pk):
    context = {}
    try:
        category = Category.objects.get(pk=pk, is_deleted=False)
    except Category.DoesNotExist:
        category = None

    items = Item.objects.filter(is_deleted=False, category=category, provider=request.user.company_admin.company)

    page = request.GET.get('page', 1)
    paginator = Paginator(items, 20)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    context['objects'] = items
    context['category'] = category
    template_name = 'items/item_list.html'
    return render(request, template_name, context)


@login_required
@provider_required
def item_add(request, pk):
    context = {}
    try:
        category = Category.objects.get(pk=pk, is_deleted=False)
    except Category.DoesNotExist:
        messages.error(request, 'Category Not Found')
        return redirect('/')
    if category:
        form = forms.ItemCreateForm(data=request.POST or None)
        stockForm = forms.StockForm(data=request.POST or None)
        ItemFormSet = modelformset_factory(model=ItemImage, form=forms.ItemImageForm, formset=BaseItemModelFormSet)
        formset = ItemFormSet(request.POST or None, request.FILES or None, queryset=Item.objects.none())
        context['form'] = form
        context['formset'] = formset
        context['stock_form'] = stockForm
        if request.method == 'POST':
            if form.is_valid() and stockForm.is_valid() and formset.is_valid():
                data = form.save(commit=False)
                data.provider = request.user.company_admin.company
                data.category = category
                data.save()
                stock = stockForm.save(commit=False)
                stock.item = data
                stock.save()

                for image_form in formset.forms:
                    cd = image_form.cleaned_data
                    item_image = image_form.save(commit=False)
                    item_image.item = data
                    item_image.save()

                messages.success(request, 'Item Created')
                return redirect('items:list', category.pk)
    context['category'] = category
    template_name = 'items/item_add.html'
    return render(request, template_name, context)


def item_detail(request, slug):
    context = {}
    try:
        item = Item.objects.get(is_deleted=False, slug=slug)
        item_stock_count = item.stock_record.quantity

    except Item.DoesNotExist:
        item = None
        item_stock_count = None

    except Item.MultipleObjectsReturned:
        qs = Item.objects.filter(slug=slug, is_deleted=False)
        item = qs.first()
        item_stock_count = item.stock_record.quantity

    context['item_count'] = item_stock_count
    context['quantity'] = range(1, item_stock_count + 1)

    if item:
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        context['cart'] = cart_obj
        if cart_obj:
            context['items'] = cart_obj.cart_items.all()

        form = CommentForm(request.POST or None)
        quantity_form = forms.QuantityForm(request.POST or None)
        rating_form = RatingForm(request.POST or None)
        if request.method == 'POST':
            if quantity_form.is_valid():
                data = quantity_form.save(commit=False)
                data.cart = cart_obj
                data.item = item
                data.save()
                item.stock_record.quantity -= decimal.Decimal(data.quantity)
                item.stock_record.save()
                item.save()

                request.session['item_count'] = cart_obj.cart_items.all().count()
                messages.success(request, 'Item Added to Cart')
                return redirect('carts:cart')

            if rating_form.is_valid():
                rating = rating_form.save(commit=False)
                rating.item = item
                rating.fiscal_year = FiscalYear.get_active_fiscal_year()
                if request.user.is_authenticated:
                    if request.user.is_customer():
                        rating.user = request.user

                else:
                    if request.session['guest_email_id']:
                        guest_email_id = request.session['guest_email_id']
                        try:
                            g_mail = GuestEmail.objects.get(id=guest_email_id)
                        except GuestEmail.MultipleObjectsReturned:
                            g_mail = GuestEmail.objects.filter(id=guest_email_id).last()
                        except GuestEmail.DoesNotExist:
                            g_mail = None
                        rating.guest_user = g_mail

                rating.save()
                return HttpResponseRedirect("")

        context['form'] = form
        context['rating_form'] = rating_form
        context['quantity_form'] = quantity_form

        try:
            data = CartItem.objects.get(item=item, cart=cart_obj)
            if data:
                context['data'] = 1

        except CartItem.MultipleObjectsReturned:
            data = CartItem.objects.filter(item=item, cart=cart_obj).first()
            if data:
                context['data'] = 1
        except CartItem.DoesNotExist:
            data = None
            if data:
                context['data'] = 1
            else:
                context['data'] = 0

        comments = Comment.objects.filter(item=item).order_by('-created_at')
        related_products = Item.objects.filter(is_deleted=False, category=item.category)
        context['related_products'] = related_products
        context['comments'] = comments
        ratings5 = Rating.objects.filter(is_deleted=False, item=item, rating=5).count()
        ratings4 = Rating.objects.filter(is_deleted=False, item=item, rating=4).count()
        ratings3 = Rating.objects.filter(is_deleted=False, item=item, rating=3).count()
        ratings2 = Rating.objects.filter(is_deleted=False, item=item, rating=2).count()
        ratings1 = Rating.objects.filter(is_deleted=False, item=item, rating=1).count()
        context['ratings5'] = ratings5
        context['ratings4'] = ratings4
        context['ratings3'] = ratings3
        context['ratings2'] = ratings2
        context['ratings1'] = ratings1
        if request.user.is_authenticated:
            if request.user.is_customer():
                try:
                    is_rated = Rating.objects.get(is_deleted=False, item=item, user=request.user)
                except Rating.DoesNotExist:
                    is_rated = None
                if is_rated:
                    context['rate'] = is_rated
                    context['is_rated'] = True
    try:
        ratings = Rating.objects.filter(item=item, is_deleted=False)
    except :
        ratings = None
        
    if ratings:
        total_ratings = ratings.aggregate(Sum('rating'))
        rating_total = total_ratings['rating__sum']
        avg_rating = rating_total/ratings.count()
        rating_percentage = (avg_rating/5)*100
        print(rating_percentage)
        context['rating_percentage'] = rating_percentage
        context['avg_rating'] = avg_rating
        context['rating_total'] = rating_total
    context['item'] = item
    template_name = 'items/item_detail.html'
    return render(request, template_name, context)


@login_required
@provider_required
def item_update(request, slug):
    context = {}
    try:
        item = Item.objects.get(is_deleted=False, slug=slug)
        item_stock_count = item.stock_record.quantity
    except Item.DoesNotExist:
        item = None
    except Item.MultipleObjectsReturned:
        qs = Item.objects.filter(slug=slug, is_deleted=False)
        item = qs.first()
    if item:
        stock_record = item.stock_record
    else:
        stock_record = None

    form = forms.ItemCreateForm(data=request.POST or None, instance=item)
    stockForm = forms.StockForm(data=request.POST or None, instance=stock_record)
    ItemFormSet = modelformset_factory(model=ItemImage, form=forms.ItemImageForm, formset=BaseItemModelFormSet)
    formset = ItemFormSet(request.POST or None, request.FILES or None, queryset=ItemImage.objects.none())
    if request.method == 'POST':
        if form.is_valid() and stockForm.is_valid() and formset.is_valid():
            form.save()
            stockForm.save()
            for image_form in formset.forms:
                cd = image_form.cleaned_data
                item_image = image_form.save(commit=False)
                item_image.item = item
                item_image.save()

            messages.success(request, 'Item Updated')
            return redirect('items:list', item.category.pk)
    images = ItemImage.objects.filter(item=item)
    context['images'] = images

items/templates/items/category_select.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    Select Category | {{ block.super }}
{% endblock %}
{% block breadcrumbLink %}
    {% if request.user.is_authenticated %}
        <li class="breadcrumb-item active">Select Category </li> {% endif %}
{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card">
            <div class="body table-responsive">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12  col-xs-12 text-left ">
                        <h5 class="">Category | <small>Select Category to see items inside the category</small></h5>
                    </div>
                    
                </div>

                <table class="table mt-2">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">S.N.</th>
                        <th scope="col">Category</th>

                        <th style="max-width:15%"></th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for object in objects %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td> <a href="{% url 'items:list' object.pk %}">{{ object.name }}</a>
                            </td>

                         <td class=''>
                            <a href="{% url 'items:list' object.pk %}">See Items</a>
                            </td> 

                        </tr>
                    {% empty %}
                        <tr>
                            {% if request.GET.q %}
                                <td class="text-danger text-center" colspan="8"><h5>No Record Found ।</h5></td>
                            {% else %}
                                <td class="text-danger text-center" colspan="8"><h5>No any Data on Database Yet</h5></td>
                            {% endif %}
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
                {% include 'snippets/pagination.html'  with datas=fiscal_years %}
            </div>
        </div>
    </div>

{% endblock %}

items/templates/items/item_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Items | {{ block.super }}
{% endblock %}
{% block breadcrumbLink %}
    {% if request.user.is_authenticated %}
        <li class="breadcrumb-item"><a href="{% url 'items:category_select' %}">Select Category</a></li>
        <li class="breadcrumb-item active">Items - {{ category.name }}</li> {% endif %}
{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="card">
            <div class="body table-responsive">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12  col-xs-12 text-left ">
                        <h5 class="">Items |
                            <small>{{ category.name }}</small>
                        </h5>
                    </div>
                    <div class=" offset-lg-5  col-lg-3 col-md-6 col-sm-12 col-xs-12  text-right float-right ">
                        <a href="{% url 'items:create' category.pk %}" class="btn btn-primary btn-circle-lg "> <i
                                class="fa fa-plus"></i></a>

                    </div>
                </div>

                <table class="table mt-2">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">S.N.</th>
                        <th scope="col">Name</th>
                        <th>Price</th>
                        <th>Discount %</th>
                        <th>Discounted Price</th>
                        <th>Stock</th>

                        <th style="max-width:15%"></th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for object in objects %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td>{{ object.name }}
                            </td>
                            <td>{{ object.stock_record.price_excl_tax }}</td>
                            <td>{{ object.stock_record.discount_percentage }}</td>
                            <td>{{ object.stock_record.discounted_price }}</td>
                            <td>{{ object.stock_record.quantity }}</td>

                            <td class='text-right'>
                                <a href="{% url 'items:update' object.slug %}" class='btn btn-primary'>Edit</a>

                            </td>

                        </tr>
                    {% empty %}
                        <tr>
                            {% if request.GET.q %}
                                <td class="text-danger text-center" colspan="8"><h5>No Record Found ।</h5></td>
                            {% else %}
                                <td class="text-danger text-center" colspan="8"><h5>No any Data on Database Yet</h5>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
                {% include 'snippets/pagination.html'  with data=objects %}
            </div>
        </div>
    </div>

{% endblock %}