addresses/urls.py
from django.urls import path

from addresses import views
app_name = 'addresses'

urlpatterns = [
    path('shipping_address',views.shipping_address, name='shipping_address'),
    path('billing_address',views.billing_address, name='billing_address')
]

carts/urls.py
from django.urls import path
from carts import views
app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('item_remove_cart/<int:pk>/', views.item_remove_cart, name='item_remove_cart'),
    path('item_quantity_minus/<int:pk>/', views.item_quantity_minus, name='item_quantity_minus'),
    path('item_quantity_plus/<int:pk>/', views.item_quantity_plus ,name='item_quantity_plus'),
    
    

]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from carts.views import success
from pages import views
from users.views import guest_register_view, register_page, login_admin

urlpatterns = [
                  path('', views.home, name='home'),
                  path('admin/', admin.site.urls),
                  path('addresses/', include('addresses.urls')),
                  path('users/', include('users.urls')),
                  path('cart/', include('carts.urls')),
                  path('companies/', include('companies.urls.companies')),
                  path('company_users/', include('companies.urls.company_users')),
                  path('comments/', include('comments.urls')),
                  path('categories/', include('categories.urls')),
                  path('data-analysis/', include('data_analysis.urls')),
                  path('fiscal-years/', include('settings.urls.fiscal_years')),
                  path('guest_register/', guest_register_view,
                       name='guest_register'),
                  path('items/', include('items.urls')),
                  path('login_admin/', login_admin, name='login_admin'),
                  path('orders/', include('orders.urls')),
                  path('ratings/', include('ratings.urls')),
                  path('refunds/', include('refunds.urls')),
                  path('register/', register_page, name='register'),
                  path('success/', success, name='success'),
                  path('search_products/', views.search_products,
                       name='search_products'),
                  path('api/v1/data/', include('data_analysis.api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('change_password/', views.user_password_change, name='user_password_change'),
    path('change_sidebar_status/', views.change_sidebar_status, name="sidebar_status"),
    path('register/',views.register_page,name='register'),
    path('profile/', views.profile, name='profile'),
    path('load_profile/',views.load_profile, name='load_profile'),
    path('load_shipping/',views.load_shipping, name='load_shipping'),
  
     
    # url(r'^confirm_email/$', views.user_email_confirm, name='email_confirm'),
]

addresses/models.py
from django.db import models
from billings.models import BillingProfile
from model_utils import Choices

ADDRESS_TYPES = Choices(
    'billing',
    'shipping',
)


class Address(models.Model):
    billing_profile = models.ForeignKey(BillingProfile, related_name='addresses', on_delete=models.CASCADE)
    address_type = models.CharField(max_length=120, choices=ADDRESS_TYPES)
    address_line_1 = models.CharField(max_length=120)
    address_line_2 = models.CharField(max_length=120, null=True, blank=True)
    city = models.CharField(max_length=120)
    country = models.CharField(max_length=120, default='Nepal')
    postal_code = models.CharField(max_length=120)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}-{}'.format(self.billing_profile, self.address_type)

    def get_address(self):
        return "{line1}\n{line2}\n{city}\n, {postal}\n{country}".format(
            line1=self.address_line_1,
            line2=self.address_line_2 or "",
            city=self.city,
            postal=self.postal_code,
            country=self.country
        )

    class Meta:
        db_table = 'addresses_address'
        verbose_name = 'Address'
        verbose_name_plural = 'Addresses'

addresses/forms.py
from django import forms

from addresses.models import Address
class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            # 'billing_profile',
            # 'address_type',
            'address_line_1',
            'address_line_2',
            'city',
            'country',
            
            'postal_code'
        ]

        widgets = {
            'address_line_1' : forms.TextInput(attrs={'class':'form-control'}),
            'address_line_2' : forms.TextInput(attrs={'class':'form-control'}),
            'city' : forms.TextInput(attrs={'class':'form-control'}),
            
            'postal_code' : forms.TextInput(attrs={'class':'form-control'}),
        }

addresses/views.py
from django.contrib import messages
from django.shortcuts import redirect, render

from addresses.models import Address
from billings.models import BillingProfile
from .forms import AddressForm


def shipping_address(request):
    context = {}
    shipping_address_id = request.session.get('shipping_address_id', None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    try:
        if request.user.is_authenticated:
            address_instance = Address.objects.get(is_deleted=False, address_type='shipping',
                                                   billing_profile=billing_profile)
        else:
            address_instance = Address.objects.get(is_deleted=False, address_type='shipping',
                                                   billing_profile=billing_profile, id=shipping_address_id)

    except Address.DoesNotExist:
        address_instance = None
    except Address.MultipleObjectsReturned:
        if request.user.is_authenticated:
            qs = Address.objects.filter(is_deleted=False, address_type='shipping', billing_profile=billing_profile)
            address_instance = qs.last()
        else:
            qs = Address.objects.filter(is_deleted=False, address_type='shipping', billing_profile=billing_profile,
                                        id=shipping_address_id)
            address_instance = qs.last()

    form = AddressForm(request.POST or None, instance=address_instance or None)

    if billing_profile is not None:
        if request.method == 'POST':
            if form.is_valid():
                instance = form.save(commit=False)
                instance.address_type = 'shipping'
                instance.billing_profile = billing_profile
                instance.save()
                request.session["shipping_address_id"] = instance.id
                messages.success(request, 'Shipping Address has been Added')
                return redirect('addresses:billing_address')
    else:
        print("Error here")
        return redirect("carts:checkout")

    context['address_form'] = form
    return render(request, 'addresses/shipping_address.html', context)


def billing_address(request):
    context = {}
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None
    billing_address_id = request.session.get('billing_address_id', None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

    try:
        billing_address_instance = Address.objects.get(is_deleted=False, address_type='billing',
                                                       billing_profile=billing_profile, id=billing_address_id)
    except Address.MultipleObjectsReturned:
        qs = Address.objects.filter(is_deleted=False, address_type='billing', billing_profile=billing_profile,
                                    id=billing_address_id)
        billing_address_instance = qs.last()
    except Address.DoesNotExist:
        billing_address_instance = None
    form = AddressForm(request.POST or None, instance=billing_address_instance or None)

    if billing_profile is not None:
        if request.method == 'POST':
            if form.is_valid():
                data = form.save(commit=False)
                data.address_type = 'billing'
                data.billing_profile = billing_profile
                data.save()
                request.session["billing_address_id"] = data.id
                messages.success(request, 'Billing Address has been Added')
                return redirect("carts:checkout")
    else:
        print("Error here")
        return redirect("carts:checkout")

    context['billing_address_form'] = form
    return render(request, 'addresses/billing_address.html', context)

addresses/templates/addresses/billing_address.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block  content %}
    {% block breadcrumbHead %}
    {% endblock %}
    <div class="container-fluid">
        <div class="row mt-5">
            <div class="col-12">
                <div class="django-messages mt-2">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                <strong></strong> {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row mt-5">

            <div class="col-lg-6 offset-lg-3">
                <div class="card">
                    <div class="card-body">
                        <h5>Billing Address : </h5>
                        <!-- action='{% if action_url %}{{ action_url }}{% else %}{% url "users:login_user" %}{% endif %}' -->
                        <form id='id_billing_form' method='POST'>
                            {% csrf_token %}

                            <input type='hidden' name='next' value='{{ request.build_absolute_uri }}'/>
                            <input type='hidden' name='address_type' value='billing'/>

                            <div class=" form-group row">
                                                        <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if billing_address_form.address_line_1.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ billing_address_form.address_line_1 | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ billing_address_form.address_line_1.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field billing_address_form.address_line_1 class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ billing_address_form.address_line_1.label }} <span
                                                class="text-danger">*</span></label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                                            <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                    class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if billing_address_form.address_line_2.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ billing_address_form.address_line_2 | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ billing_address_form.address_line_2.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field billing_address_form.address_line_2 class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ billing_address_form.address_line_2.label }} </label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                                            <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                    class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if billing_address_form.city.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ billing_address_form.city | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ billing_address_form.city.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field billing_address_form.city class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ billing_address_form.city.label }} </label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                                            <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                    class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if billing_address_form.country.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ billing_address_form.country | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ billing_address_form.country.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field billing_address_form.country class='form-control' placeholder='Country' required='required' %}

                                    </div>
                                {% endif %}
                            </div>


                            <div class=" form-group row">
                                                            <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                    class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if billing_address_form.postal_code.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ billing_address_form.postal_code | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ billing_address_form.postal_code.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field billing_address_form.postal_code class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ billing_address_form.postal_code.label }} </label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                <div class=" offset-lg-1 col-lg-6 col-md-8 col-sm-8 col-12">
                                    <button type="submit" class='btn btn-block btn-lg btn-primary' name="submit">Save

                                    </button>
                                </div>
                                <div class=" ">
                                    <button type="" class='btn btn-block btn-lg btn-warning' name="copy"
                                            id='id_copy_address'>Same as Shipping Address

                                    </button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>


        </div>

    </div>


    {% block extra_script %}
        <script>
            $(function () {
                $('#id_copy_address').click(function (e) {
                    e.preventDefault();
                    url = '/users/load_shipping/'
                    $.ajax({
                        url: url,
                        dataType: 'json',
                        cache: false,
                        success: function (data) {
                            $('#id_address_line_1').val(data.fields.address_line_1)
                            $('#id_address_line_2').val(data.fields.address_line_2)
                            $('#id_city').val(data.fields.city)
                            $('#id_country').val(data.fields.country)
                            $('#id_postal_code').val(data.fields.postal_code)
                            console.log(data)

                        }
                    });
                });

            })
        </script>

    {% endblock %}

{% endblock %}

addresses/templates/addresses/shipping_address.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block  content %}
    {% block breadcrumbHead %}
    {% endblock %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-12">
                <div class="django-messages mt-2">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                <strong></strong> {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="row mt-5">
            <div class="col-lg-6 offset-lg-3">

                <div class="card">
                    <div class="card-body">
                        <h5>Shipping Address : </h5>

                        <form id='id_shipping_form' method='POST'>
                            {% csrf_token %}

                            <input type='hidden' name='next' value='{{ request.build_absolute_uri }}'/>
                            <input type='hidden' name='address_type' value='shipping'/>
                            <div class=" form-group row">
                                                            <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                    class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if address_form.address_line_1.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ address_form.address_line_1 | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ address_form.address_line_1.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field address_form.address_line_1 class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ address_form.address_line_1.label }} <span
                                                class="text-danger">*</span></label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                                                <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                        class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if address_form.address_line_2.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ address_form.address_line_2 | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ address_form.address_line_2.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field address_form.address_line_2 class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ address_form.address_line_2.label }} </label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                                                <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                        class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if address_form.city.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ address_form.city | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ address_form.city.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field address_form.city class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ address_form.city.label }} </label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                                                <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                        class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if address_form.country.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ address_form.country | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ address_form.country.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field address_form.country class='form-control' placeholder='Country' required='required' %}

                                    </div>
                                {% endif %}
                            </div>
                            <div class=" form-group row">
                                                                <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                                                        class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>

                                {% if address_form.postal_code.errors %}
                                    <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                        {{ address_form.postal_code | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ address_form.postal_code.errors }}
                                        </div>
                                    </div>
                                {% else %}

                                    <div class="col-lg-10 offset-lg-1 col-md-8 col-sm-8 col-12">
                                        {% render_field address_form.postal_code class='form-control' placeholder='' required='required' %}
                                        <label for="" class="">{{ address_form.postal_code.label }} </label>
                                    </div>
                                {% endif %}
                            </div>

                            <div class=" form-group row">
                                <div class=" offset-lg-1 col-lg-10 col-md-8 col-sm-8 col-12">
                                    <button type="submit" class='btn btn-block btn-lg btn-primary' name="submit">
                                        Continue
                                    </button>
                                    {% if request.user.is_authenticated  and request.user.userprofile %}
                                        <button id="id_load_profile" class="btn btn-block btn-lg btn-secondary">Load
                                            From
                                            Profile
                                        </button>
                                    {% endif %}

                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>

    </div>

    {% block extra_script %}
        <script>
            $(function () {
                $('#id_load_profile').click(function (e) {
                    e.preventDefault();
                    url = '/users/load_profile/'
                    $.ajax({
                        url: url,
                        dataType: 'json',
                        cache: false,
                        success: function (data) {
                            $('#id_address_line_1').val(data.fields.address_line_1)
                            $('#id_address_line_2').val(data.fields.address_line_2)
                            $('#id_city').val(data.fields.city)
                            $('#id_country').val(data.fields.country)
                            $('#id_postal_code').val(data.fields.postal_code)
                            console.log(data)
                        }
                    });
                });
            })
        </script>

    {% endblock %}

{% endblock %}