carts/urls.py
from django.urls import path
from carts import views
app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('item_remove_cart/<int:pk>/', views.item_remove_cart, name='item_remove_cart'),
    path('item_quantity_minus/<int:pk>/', views.item_quantity_minus, name='item_quantity_minus'),
    path('item_quantity_plus/<int:pk>/', views.item_quantity_plus ,name='item_quantity_plus'),
    
    

]

categories/urls.py
from django.urls import path

from categories import views

app_name = 'categories'

urlpatterns = [
    path('', views.category_list, name='list'),
    path('create/', views.category_create, name='create'),
    path('<slug:slug>/', views.items_category, name='items_category'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from carts.views import success
from pages import views
from users.views import guest_register_view, register_page, login_admin

urlpatterns = [
                  path('', views.home, name='home'),
                  path('admin/', admin.site.urls),
                  path('addresses/', include('addresses.urls')),
                  path('users/', include('users.urls')),
                  path('cart/', include('carts.urls')),
                  path('companies/', include('companies.urls.companies')),
                  path('company_users/', include('companies.urls.company_users')),
                  path('comments/', include('comments.urls')),
                  path('categories/', include('categories.urls')),
                  path('data-analysis/', include('data_analysis.urls')),
                  path('fiscal-years/', include('settings.urls.fiscal_years')),
                  path('guest_register/', guest_register_view,
                       name='guest_register'),
                  path('items/', include('items.urls')),
                  path('login_admin/', login_admin, name='login_admin'),
                  path('orders/', include('orders.urls')),
                  path('ratings/', include('ratings.urls')),
                  path('refunds/', include('refunds.urls')),
                  path('register/', register_page, name='register'),
                  path('success/', success, name='success'),
                  path('search_products/', views.search_products,
                       name='search_products'),
                  path('api/v1/data/', include('data_analysis.api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path

from items import views

app_name = 'items'

urlpatterns = [
    path('', views.category_select, name='category_select'),
    path('<int:pk>', views.item_list, name='list'),
    path('<int:pk>/create', views.item_add, name='create'),
    path('<slug:slug>', views.item_detail, name='detail'),
    path('update/<slug:slug>/', views.item_update, name='update'),
    path('<int:pk>/image_remove', views.image_remove, name='image_remove'),
]

categories/models.py
from django.db import models

from ecommerce.utils import CustomModelManager, CustomModelQuerySet,  unique_slug_generator
from django.db.models.signals import pre_save

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=120, error_messages={'max_length':'Length Should Not Exceed 120 Characters '})
    slug = models.SlugField(max_length=100, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CustomModelManager.from_queryset(CustomModelQuerySet)()

    class Meta:
        db_table = 'categories_category'
        verbose_name = 'Category'
        

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

def category_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(category_pre_save_receiver, sender=Category)

categories/forms.py
from django import forms

from categories.models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'name',
            'description',
        ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': 'required', 'placeholder': ''}),
            'description': forms.Textarea(
                attrs={'class': 'form-control', 'required': 'required', 'placeholder': 'Description ...'}),

        }

        labels = {
            'name': 'Category Name',
            'description': 'Description'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

categories/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from categories import forms
from categories.models import Category
from users.decorators import admin_required


@login_required
@admin_required
def category_list(request):
    context = {}
    objects = Category.objects.all_active()
    template_name = 'categories/category_list.html'

    context['objects'] = objects
    return render(request, template_name, context)


@login_required
@admin_required
def category_create(request):
    context = {}
    form = forms.CategoryForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            messages.success(request, 'Category Created Successfully . ')
            return redirect('categories:list')
    context['form'] = form
    return render(request, 'categories/category_create.html', context)


def items_category(request, slug):
    context = {}
    try:
        category = Category.objects.get(slug=slug)
    except Category.MultipleObjectsReturned:
        category = Category.objects.filter(slug=slug).first()
    except Category.DoesNotExist:
        category = None
    if category:
        items = category.items.all_active()
    context['products'] = items
    context['categories'] = Category.objects.all_active()
    template_name = 'categories/items_category.html'
    return render(request, template_name, context)

categories/templates/categories/category_create.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}
    New Fiscal Year | {{block.super}}
{% endblock %}

{% block breadcrumbLink %}
    {% if request.user.is_authenticated %}
        <li class="breadcrumb-item"><a href="{% url 'categories:list' %}">
            Categories
        </a></li> {% endif %}
    <li class="breadcrumb-item active">New</li>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="table-responsive">
        <div class="card ">
            <div class="card-body">
                {% if form.non_field_errors %}
                    <div class="row">
                        <div class="col-12">
                            <div class="alert alert-danger">
                                <ul>
                                    {% for error in form.non_field_errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="row ">
                    <div class="col-lg-10 col-md-12 col-sm-12 col-12">
                        <form method="post">
                            {% csrf_token %}


                            <div class=" form-group row">
                                    <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                            class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>
    
                                    {% if form.name.errors %}
                                        <div class="col-lg-4 col-md-2 col-sm-2 col-4 col-1">
                                            {{ form.name | add_class:"is-invalid" }}
                                            <div class="invalid-feedback">
                                                {{ form.name.errors }}
                                            </div>
                                        </div>
                                    {% else %}
    
                                        <div class="col-lg-6 col-md-8 col-sm-8 col-12">
                                            {{ form.name }}
                                            <label for="" class="">Name<span
                                                class="text-danger">*</span></label>
                                        </div>
                                    {% endif %}
                                </div>
                            
                            
                            <div class=" form-group row">
                                    <span class="col-lg-4 col-md-2 col-sm-2 col-1"><span
                                            class=" float-lg-right float-md-right float-sm-right float-right"> </span></span>
    
                                    {% if form.description.errors %}
                                        <div class="col-lg-4 col-md-2 col-sm-2 col-4">
                                            {{ form.address | add_class:"is-invalid" }}
                                            <div class="invalid-feedback">
                                                {{ form.description.errors }}
                                            </div>
                                        </div>
                                    {% else %}
    
                                        <div class="col-lg-6 col-md-8 col-sm-8 col-12">
                                            {{ form.description }}
                                           
                                        </div>
                                    {% endif %}
                                </div>

                                 
                           
                            <div class=" form-group row">
                                <div class="offset-sm-2 offset-lg-4 col-lg-6 col-md-8 col-sm-8 col-12">
                                    <button type="submit" class='btn btn-submit btn-block btn-primary' name="submit">Save
                                        
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

categories/templates/categories/category_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Categories | {{ block.super }}
{% endblock %}
{% block breadcrumbLink %}
    {% if request.user.is_authenticated %}
        <li class="breadcrumb-item active">Categories</li> {% endif %}
{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                    <div class="card">
                            <div class="body table-responsive">
                                <div class="row">
                                    <div class="col-lg-4 col-md-6 col-sm-12  col-xs-12 text-left ">
                                        <h5 class="">Categories</h5>
                                    </div>
                                    <div class=" offset-lg-5  col-lg-3 col-md-6 col-sm-12 col-xs-12  text-right float-right ">
                                        <a href="{% url 'categories:create' %}" class="btn btn-primary btn-circle-lg ">  <i class="fa fa-plus"></i></a>
                
                                    </div> 
                                </div>
                
                                <table class="table mt-2">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">S.N.</th>
                                        <th scope="col">Name</th>
                                        <th>Description</th>
                                      
                                        <th style="max-width:15%"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                
                                    {% for object in objects %}
                                    
                                        <tr>
                                            <td scope="row">{{ forloop.counter }}</td>
                                            <td>{{ object.name }}
                                            </td>
                                            
                                            <td>{{object.description}}</td>
                                            
                                         <td class='text-right'>
                                            
                                            </td> 
                
                                        </tr>
                                    {% empty %}
                                        <tr>
                                            {% if request.GET.q %}
                                                <td class="text-danger text-center" colspan="8"><h5>No Records Found </h5></td>
                                            {% else %}
                                                <td class="text-danger text-center" colspan="8"><h5>No record on database </h5></td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                
                
                                    </tbody>
                                </table>
                                {% include 'snippets/pagination.html'  with datas=objects %}
                            </div>
                        </div>
            </div>
        </div>    
    </div>

{% endblock %}

categories/templates/categories/items_category.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block extra_stylesheet %}
    <style>
        body {
            background: white;
            width: 100%;

        }

        input[type=text] {
            width: 100%;
        }

        .view {
            position: relative;
            cursor: default;
        }

        .view, .view .mask, .waves-effect {
            overflow: hidden;
        }

        .hoverable:hover {
            -webkit-box-shadow: 0 8px 17px 0 rgba(0, 0, 0, .2), 0 6px 20px 0 rgba(0, 0, 0, .19);
            box-shadow: 0 8px 17px 0 rgba(0, 0, 0, .2), 0 6px 20px 0 rgba(0, 0, 0, .19);
            -webkit-transition: all .55s ease-in-out;
            -o-transition: all .55s ease-in-out;
            transition: all .55s ease-in-out;
        }

        .nav-justified .nav-item {
            -ms-flex-preferred-size: 0;
            flex-basis: 0;
            -ms-flex-positive: 1;
            flex-grow: 1;
            text-align: center;
        }

        .md-tabs .nav-item.open .nav-link, .md-tabs .nav-link.active {
            background-color: rgba(0, 0, 0, .2);
            color: #fff;
            -webkit-transition: all 1s;
            -o-transition: all 1s;
            transition: all 1s;
            -webkit-border-radius: .25rem;
            border-radius: .25rem;
        }

        .md-tabs .nav-link {
            -webkit-transition: all .4s;
            -o-transition: all .4s;
            transition: all .4s;
            border: 0;
            color: #fff;
        }

        .dark-grey-text, .dark-grey-text:focus, .dark-grey-text:hover {
            color: #4f4f4f !important;
        }

        .font-weight-bold {
            font-weight: 700 !important;
        }

        .grey.lighten-3 {
            background-color: #eee !important;
        }

        .view .mask {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            width: 100%;
            height: 100%;
            background-attachment: fixed;
        }

        .z-depth-1 {
            -webkit-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0 rgba(0, 0, 0, .12);
            box-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0 rgba(0, 0, 0, .12);
        }

        .md-tabs {
            box-shadow: 0 5px 11px 0 rgba(0, 0, 0, .18), 0 4px 15px 0 rgba(0, 0, 0, .15);
            border: 0;
            padding: .7rem;
            margin-left: 1rem;
            margin-right: 1rem;
            margin-bottom: -20px;
            background-color: #2bbbad;
            z-index: 1;
            position: relative;
            -webkit-border-radius: .25rem;
            border-radius: .25rem;
        }

        .rating {
            color: #ffa000;
            list-style-type: none;
            padding: 0;
        }

        .rating li, .side-nav .social li {
            display: inline-block;
        }
    </style>

{% endblock extra_stylesheet %}
{% block content %}
    <div class="container">
        <!-- Grid row -->
        <div class="row pt-4">

            <!-- Content -->
            <div class="col-lg-12">

                <!-- Categories & Adv -->
                <section class="">

                    <!-- Grid row -->
                    <div class="row">

                        <!--Grid column-->
                        <div class="col-lg-3 col-md-12 mb-4">

                            <!-- Section: Categories -->
                            <section class="section">

                                <ul class="list-group z-depth-1">
                                    {% for category in categories %}
                                        <li class="list-group-item d-flex
                                    justify-content-between align-items-center">
                                            <a class="dark-grey-text font-small"
                                               href="{% url 'categories:items_category' category.slug %}"
                                               style="color:black;">

                                                {{ category }}</a>
                                            <a href=""></a>
                                            <span class="badge badge-danger badge-pill">{{ category.items.count }}</span>
                                        </li>
                                    {% endfor %}

                                </ul>


                            </section>
                            <!-- Section: Categories -->


                        </div>
                        <!--Grid column-->

                        <!--Grid column-->
                        <div class="col-lg-9 col-md-12 pb-lg-5 mb-4">
                            <!--Image -->
                            <div class="row">
                                {% for product in products %}
                                    <div class="col-lg-4 col-md-12 mb-4">
                                        <!--Card-->

                                        <div class="card" style="height: 320px;">
                                            <!--Card image-->
                                            <div class="view ">
                                                {% for i in product.item_images.all %}
                                                    {% if forloop.last %}
                                                        {% if i.document %}
                                                            <a href="{% url 'items:detail' product.slug %}"> <img
                                                                    src="{{ i.document.url }}" height="40px"
                                                                    class="img-fluid " alt='product image here'> </a>
                                                        {% endif %}
                                                    {% endif %}
                                                {% empty %}
                                                    <img src="{% static 'images/default.jpg' %}" height="40px"
                                                         class="img-fluid " alt='product image here'>

                                                {% endfor %}


                                                <a>
                                                    <div class="mask rgba-white-slight waves-effect waves-light"></div>
                                                </a>
                                            </div>
                                            <!--Card image-->

                                            <!--Card content-->
                                            <div class="card-body">
                                                <!--Category & Title-->

                                                <h5 class="card-title mb-1">
                                                    <strong>
                                                        <a href="{% url 'items:detail' product.slug %}"> {{ product.name }}</a>
                                                    </strong>
                                                </h5>


                                                <!--Card footer-->
                                                <div class="card-footer pb-0">
                                                    <div class="row mb-0">
                                                        <h5 class="mb-0 pb-0 mt-1 font-weight-bold"><span
                                                                class="red-text"><strong>Rs {{ product.stock_record.discounted_price }}</strong></span>
                                                            {% if product.stock_record.discounted_price != product.stock_record.price_excl_tax %}
                                                                <span class="grey-text"><small><s>{{ product.stock_record.price_excl_tax }}</s></small></span>
                                                            {% endif %}
                                                        </h5>
                                                    </div>
                                                </div>


                                            </div>
                                            <!--Card content-->

                                        </div>

                                        <!--Card-->
                                    </div>
                                {% endfor %}
                            </div>

                            <!--Image -->
                        </div>
                        <!--Grid column-->

                    </div>
                    <!--Grid row-->

                </section>
                <!-- Categories & Adv -->


            </div>
            <!-- /.Content -->

        </div>
        <!-- /Grid row -->
    </div>


{% endblock %}